use std::collections::{HashMap, HashSet};

use crate::chord::Triad;
use crate::transform::{apply, PLR, PLRWord};

/// Compute the orbit of a triad under all PLR transformations.
/// Returns all 24 triads (the PLR group acts transitively).
pub fn orbit(start: Triad) -> HashSet<Triad> {
    let mut visited = HashSet::new();
    let mut stack = vec![start];
    while let Some(t) = stack.pop() {
        if visited.insert(t) {
            for &op in &[PLR::P, PLR::L, PLR::R] {
                let next = apply(op, t);
                if !visited.contains(&next) {
                    stack.push(next);
                }
            }
        }
    }
    visited
}

/// Compute the orbit of a triad under a subgroup generated by the given ops.
pub fn suborbit(start: Triad, generators: &[PLR]) -> HashSet<Triad> {
    let mut visited = HashSet::new();
    let mut stack = vec![start];
    while let Some(t) = stack.pop() {
        if visited.insert(t) {
            for &op in generators {
                let next = apply(op, t);
                if !visited.contains(&next) {
                    stack.push(next);
                }
            }
        }
    }
    visited
}

/// Build the full Cayley table: for each triad, what results from each PLR op.
pub fn cayley_table() -> HashMap<Triad, HashMap<PLR, Triad>> {
    let mut table = HashMap::new();
    for t in Triad::all() {
        let mut row = HashMap::new();
        for &op in &[PLR::P, PLR::L, PLR::R] {
            row.insert(op, apply(op, t));
        }
        table.insert(t, row);
    }
    table
}

/// Find the PLRWord that transforms `from` into `to` via brute-force search.
/// Uses BFS over the PLR graph.
pub fn find_word(from: Triad, to: Triad) -> Option<PLRWord> {
    if from == to {
        return Some(PLRWord::new());
    }
    let mut visited = HashSet::new();
    // (current triad, word to get there)
    let mut queue = std::collections::VecDeque::new();
    visited.insert(from);
    queue.push_back((from, PLRWord::new()));

    while let Some((current, word)) = queue.pop_front() {
        for &op in &[PLR::P, PLR::L, PLR::R] {
            let next = apply(op, current);
            if next == to {
                let mut result = word.clone();
                result.push(op);
                return Some(result);
            }
            if visited.insert(next) {
                let mut next_word = word.clone();
                next_word.push(op);
                queue.push_back((next, next_word));
            }
        }
    }
    None
}

/// Verify the group axioms for the PLR group action on triads.
pub fn verify_group_axioms() -> bool {
    // Closure: all PLR ops map triads to triads (guaranteed by construction)
    // Identity: P² = L² = R² = identity (involution property)
    for t in Triad::all() {
        // Identity via PP
        if apply(PLR::P, apply(PLR::P, t)) != t {
            return false;
        }
        if apply(PLR::L, apply(PLR::L, t)) != t {
            return false;
        }
        if apply(PLR::R, apply(PLR::R, t)) != t {
            return false;
        }
    }
    // Transitivity: orbit of any triad = all 24 triads
    let orbit_c = orbit(Triad::all()[0]);
    if orbit_c.len() != 24 {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::chord::Quality;

    #[test]
    fn test_orbit_full() {
        let c = Triad::new_unchecked(0, Quality::Major);
        let orb = orbit(c);
        assert_eq!(orb.len(), 24);
    }

    #[test]
    fn test_orbit_transitive() {
        let c = Triad::new_unchecked(0, Quality::Major);
        let fs = Triad::new_unchecked(6, Quality::Major);
        let orb = orbit(c);
        assert!(orb.contains(&fs));
    }

    #[test]
    fn test_suborbit_p_only() {
        // P alone: orbit is just {triad, parallel}
        let c = Triad::new_unchecked(0, Quality::Major);
        let orb = suborbit(c, &[PLR::P]);
        assert_eq!(orb.len(), 2);
    }

    #[test]
    fn test_find_word_identity() {
        let c = Triad::new_unchecked(0, Quality::Major);
        let word = find_word(c, c).unwrap();
        assert!(word.is_empty());
    }

    #[test]
    fn test_find_word_p() {
        let c = Triad::new_unchecked(0, Quality::Major);
        let cm = Triad::new_unchecked(0, Quality::Minor);
        let word = find_word(c, cm).unwrap();
        assert_eq!(word.len(), 1);
        assert_eq!(word.ops[0], PLR::P);
    }

    #[test]
    fn test_find_word_applies_correctly() {
        let c = Triad::new_unchecked(0, Quality::Major);
        let fs = Triad::new_unchecked(6, Quality::Minor);
        let word = find_word(c, fs).unwrap();
        assert_eq!(word.apply(c), fs);
    }

    #[test]
    fn test_group_axioms() {
        assert!(verify_group_axioms());
    }
}
